# Place all the behaviors and hooks related to the matching controller here.
# All this logic will automatically be available in application.js.
# You can use CoffeeScript in this file: http://coffeescript.org/
$(document).ready ->
  bar = $('.progress-bar')
  if parseInt(bar[0].style.width, 10) > 100
    $('.progress-bar').addClass 'progress-bar-danger'
  else if parseInt(bar[0].style.width, 10) > 75
    $('.progress-bar').removeClass('progress-bar-danger').addClass 'progress-bar-warning'
  else
    $('.progress-bar').removeClass 'progress-bar-danger'
  return

# ---
# # generated by js2coffee 2.2.0



